// Mocks generated by Mockito 5.4.5 from annotations
// in devlink_mobile_app/test/notification/data/repository_impl/notification_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:devlink_mobile_app/notification/data/data_source/notification_data_source.dart'
    as _i2;
import 'package:devlink_mobile_app/notification/data/dto/notification_dto.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NotificationDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationDataSource extends _i1.Mock
    implements _i2.NotificationDataSource {
  MockNotificationDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.NotificationDto>> fetchNotifications(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchNotifications, [userId]),
            returnValue: _i3.Future<List<_i4.NotificationDto>>.value(
              <_i4.NotificationDto>[],
            ),
          )
          as _i3.Future<List<_i4.NotificationDto>>);

  @override
  _i3.Future<bool> markAsRead(String? userId, String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [userId, notificationId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> markAllAsRead(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, [userId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteNotification(String? userId, String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [userId, notificationId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
